### ISSUE TITLE
Unlock versions of dependencies

### ISSUE THREAD

**Issue by quantori-pokidovea** [DriesSchaumont/sphinx-subprojecttoctree#35]
Current version of Sphinx is 5.1.1, requests-2.28.1.
Are there any reasons to fix version of the package dependencies?

**Comment by DriesSchaumont** [comment]
Hi @quantori-pokidovea ATM I do not see a problem to supporting sphinx 5 and unpinning requests to the major version. Sphinx 5 will need to be tested though, because this is a major version bump. I am currently on holidays, but I will have a look at this when I get back in a couple of weeks.

**Comment by DriesSchaumont** [comment]
Hi @quantori-pokidovea 0.4.0 was just released. Let me know if you run into any problems.
Dries
